#!/usr/bin/env dash

build () {
  other_opts="-fdiagnostics-color=always"
  copts="-c -std=c11 -Wall -Wextra -Wpedantic -Werror -Wshadow"
  input_files="$@"
  
  nix-shell -p gcc binutils \
            --command "gcc -g ${other_opts} ${copts} ${input_files}"
}

build "$@"
